const galleryData = [
    {
        id: "galleryIbadan",
        title: "Gallery Ibadan Training",
        images: [
            "/images/Gallery Ibadan Training/IMG_7713.jpg",
            "/images/Gallery Ibadan Training/IMG_7715.jpg",
            "/images/Gallery Ibadan Training/IMG_7738.jpg",
            "/images/Gallery Ibadan Training/IMG_7739.jpg",
            "/images/Gallery Ibadan Training/IMG_7741.jpg",
            "/images/Gallery Ibadan Training/IMG_7742.jpg",
            "/images/Gallery Ibadan Training/IMG_7743.jpg",
            "/images/Gallery Ibadan Training/IMG_7750.jpg",
            "/images/Gallery Ibadan Training/IMG_7751.jpg",
            "/images/Gallery Ibadan Training/IMG_7753.jpg",
            "/images/Gallery Ibadan Training/IMG_7759.jpg",
        ],
        description: "Our event at Ibadan.",
        category: "events",
    },
    {
        id: "galleryKaduna",
        title: "Gallery Kaduna Training",
        images: [
            "/images/Gallery Kaduna Training/IMG_5706.jpg",
            "/images/Gallery Kaduna Training/IMG_5756.jpg",
            "/images/Gallery Kaduna Training/IMG_5791.jpg",
            "/images/Gallery Kaduna Training/IMG_5798.jpg",
            "/images/Gallery Kaduna Training/IMG_5799.jpg",
            "/images/Gallery Kaduna Training/IMG_5838.jpg",
            "/images/Gallery Kaduna Training/IMG_5839.jpg",
            "/images/Gallery Kaduna Training/IMG_5852.jpg",
            "/images/Gallery Kaduna Training/IMG_6071.jpg",
            "/images/Gallery Kaduna Training/IMG_6094.jpg",
            "/images/Gallery Kaduna Training/IMG_6147.jpg",
        ],
        description: "Our event at Kaduna.",
        category: "events",
    },
    {
        id: "mastercardFoundation",
        title: "Mastercard Foundation Edtech Conference",
        images: [
            "/images/Mastercard Foundation Edtech Conference/IMG_6296.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6299.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6333.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6334.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6338.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6342.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6357.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6439.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6449.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6469.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6470.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6299.jpg",
        ],
        description: "The Mastercard Foundation Edtech conference Event.",
        category: "events",
    },
    {
        id: "adaobiOnyishi",
        title: "Adaobi Onyishi",
        images: ["/images/Teazy Tech Volunteers/Adaobi Onyishi.JPG"],
        description: "Field Representative",
        category: "volunteers",
    },
    {
        id: "ridwanAboki",
        title: "Ridwan Olalere Aboki",
        images: ["/images/Teazy Tech Volunteers/Ridwan Aboki.JPG"],
        description: "Training Facilitator",
        category: "volunteers",
    },
];
export default galleryData;
