const galleryData = [
    {
        id: "galleryIbadan",
        title: "Gallery Ibadan Training",
        images: [
            "/images/Gallery Ibadan Training/IMG_7713.jpg",
            "/images/Gallery Ibadan Training/IMG_7715.jpg",
            "/images/Gallery Ibadan Training/IMG_7738.jpg",
            "/images/Gallery Ibadan Training/IMG_7739.jpg",
            "/images/Gallery Ibadan Training/IMG_7741.jpg",
            "/images/Gallery Ibadan Training/IMG_7742.jpg",
            "/images/Gallery Ibadan Training/IMG_7743.jpg",
            "/images/Gallery Ibadan Training/IMG_7750.jpg",
            "/images/Gallery Ibadan Training/IMG_7751.jpg",
            "/images/Gallery Ibadan Training/IMG_7753.jpg",
            "/images/Gallery Ibadan Training/IMG_7759.jpg",
        ],
        description: "Our event at Ibadan.",
        category: "events",
    },
    {
        id: "galleryKaduna",
        title: "Gallery Kaduna Training",
        images: [
            "/images/Gallery Kaduna Training/IMG_5706.jpg",
            "/images/Gallery Kaduna Training/IMG_5756.jpg",
            "/images/Gallery Kaduna Training/IMG_5791.jpg",
            "/images/Gallery Kaduna Training/IMG_5798.jpg",
            "/images/Gallery Kaduna Training/IMG_5799.jpg",
            "/images/Gallery Kaduna Training/IMG_5838.jpg",
            "/images/Gallery Kaduna Training/IMG_5839.jpg",
            "/images/Gallery Kaduna Training/IMG_5852.JPG",
            "/images/Gallery Kaduna Training/IMG_6071.jpg",
            "/images/Gallery Kaduna Training/IMG_6094.jpg",
            "/images/Gallery Kaduna Training/IMG_6147.jpg",
        ],
        description: "Our event at Kaduna.",
        category: "events",
    },
    {
        id: "mastercardFoundation",
        title: "Mastercard Foundation Edtech Conference",
        images: [
            "/images/Mastercard Foundation Edtech Conference/IMG_6296.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6299.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6333.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6334.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6338.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6342.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6357.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6439.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6449.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6469.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6470.jpg",
            "/images/Mastercard Foundation Edtech Conference/IMG_6299.jpg",
        ],
        description: "The Mastercard Foundation Edtech conference Event.",
        category: "events",
    },
    {
        id: "adaobiOnyishi",
        title: "Adaobi Onyishi",
        images: ["/images/Teazy Tech Volunteers/Adaobi Onyishi.JPG"],
        description: "Field Representative",
        category: "volunteers",
    },
    {
        id: "ridwanAboki",
        title: "Ridwan Olalere Aboki",
        images: ["/images/Teazy Tech Volunteers/Ridwan Aboki.JPG"],
        description: "Training Facilitator",
        category: "volunteers",
    },
    {
        id: "emmanuelClement",
        title: "Emmanuel Clement",
        images: ["/images/Teazy Tech Volunteers/Emmanuel Clement.jpg"],
        description: "Video Content Creator",
        category: "volunteers",
    },
    {
        id: "chelseaJulius",
        title: "Chelsea Julius",
        images: ["/images/Teazy Tech Volunteers/Chelsea Julius.jpg"],
        description: "Business Assistant and Community Manager",
        category: "volunteers",
    },
    {
        id: "abimbolaAbiodun",
        title: "Abimbola Abiodun",
        images: ["/images/Teazy tech teachers/abimbola adiodun akanbi.jpg"],
        description:
            "Teazy Tech has really helped me in my online teaching. Teazy Tech always sends some really amazing EdTech tools like Photomath that I never knew existed. The community is so engaging, and we're always sent resources to ease our work for free.",
        category: "testimonials",
    },
    {
        id: "amoateyBenjamin",
        title: "Mr. Amoatey Benjamin",
        images: ["/images/Teazy tech teachers/amoatey Benjamin.jpg"],
        description:
            "Hi I am Mr. Amoatey Benjamin. A professional teacher with Ghana Education Service. My love for Professional Development led me to Teazy Tech Community, online in August 2024.I have received so much essential teaching resources from the community in the form of pictures, videos, facebook posts, ebooks and short courses.One Ebook dubbed Becoming a Tech Savvy, is one resource that has increased my joy for joining the Teazy Tech Community. All these resources have made teaching & learning outcomes so fruitful and positive. Thanks to TEAZY TECH.",
        category: "testimonials",
    },
    {
        id: "amosHappiness",
        title: "Amos Happiness",
        images: ["/images/Teazy tech teachers/Amos happiness.jpg"],
        description:
            "Joining the Teazy Tech platform has been so helpful because I always receive updates on educational apps I really need, which helps me improve my teaching methods in terms of organizing my lessons, engaging in quizzes, and creating beautiful teaching aids. I now feel much bolder as an educator",
        category: "testimonials",
    },
    {
        id: "florenceImhande",
        title: "Florence Imhande",
        images: ["/images/Teazy tech teachers/Florence imhande.jpg"],
        description:
            "I am now a Canva 'Guru' in my school thanks to Teazy tech  training a while back. I'm able to develop any resource for my lesson that I'm not able to find online myself and I'm working on  creating my portfolio because I'm hoping  to sell some of the educational resources I've been developing online. I'm sure it will be useful to others as well. Thanks so very much.",
        category: "testimonials",
    },
    {
        id: "wuaMsughve",
        title: "Wua Msughve Issac",
        images: ["/images/Teazy tech teachers/wua msughve isaac.jpg"],
        description:
            "Teazytech has become a quick go to platform for me, the short demos and introduction of important edtch tools that I never knew existed before now has made my work better as an educator. Teazy tech absolutely qualifies for every passionate teacher's companion. The demos and illustration videos are short and easy guides even for teachers that have no prior EdTech experience. With teazy tech I've come to appreciate that EdTech isn't as far fetched as I thought, I've learned engaging ways to use my android phone to navigate Google workspace and Canva to enhance my work. You definitely want to look up Teazy Tech.",
        category: "testimonials",
    },
    {
        id: "seminar",
        title: "A Seminar Event",
        images: [
            "/images/workshopPhotos/IMG_7521.jpg",
            "/images/workshopPhotos/IMG_7526.jpg",
            "/images/workshopPhotos/IMG_7528.jpg",
            "/images/workshopPhotos/IMG_7530.jpg",
            "/images/workshopPhotos/IMG_7531.jpg",
            "/images/workshopPhotos/IMG_7532.jpg",
            "/images/workshopPhotos/IMG_8138.jpg",
        ],
        description:
            "A Seminar event with TEAZY Tech as one of the partners.",
        category: "workshops",
    },
];
export default galleryData;
